image: debian:trixie-slim

build:
  script: |
    set -x
    apt-get update -o Acquire::AllowReleaseInfoChange=true -o quiet::ReleaseInfoChange=true
    apt-get --no-install-recommends --yes install make clang-format black shfmt shellcheck libglib2.0-bin help2man imagemagick build-essential pkgconf libevdev-dev libudev-dev libxkbcommon-dev libplymouth-dev
    make lint
    make test
    # make sure all files get installed
    make DESTDIR=prefix install
    diff -u <(find -type f -and -not -path '\./CHANGELOG.md' -and -not -path '\./lpc/*' -and -not -path ./Makefile -and -not -path ./LICENSE.txt -and -not -path ./README.md -and -not -path ./.gitlab-ci.yml -and -not -path '\./\.git/*' -and -not -path '\./prefix/*' -and -not -path '\./plymouth/monobar\.c' -and -not -path '\./\.mailmap' -and -not -path '\./\.gitignore' -and -not -name '\.clang-format' -print0 | xargs -0 md5sum | sort | sed 's/\.\?\/.*\///') <(env --chdir ./prefix find -type f -print0 | xargs -0 env --chdir ./prefix md5sum | sort | sed 's/\.\?\/.*\///')
