image: debian:bookworm-slim

build:
  script: |
    set -x
    apt-get update -o Acquire::AllowReleaseInfoChange=true -o quiet::ReleaseInfoChange=true
    apt-get --no-install-recommends --yes install make clang-format black shfmt shellcheck
    make lint
