#
# tuned configuration
#
[main]
include = balanced

[sysfs]
/sys/devices/platform/fb000000.gpu/devfreq/fb000000.gpu/max_freq = 1000000000
/sys/devices/platform/fb000000.gpu/devfreq/fb000000.gpu/governor = simple_ondemand
/sys/devices/platform/fb000000.gpu/devfreq/fb000000.gpu/min_freq = 300000000

