[main]
# The default PPD profile
default=balanced
battery_detection=true
sysfs_acpi_monitor=true

[profiles]
# PPD = TuneD
power-saver=reform_powersave
balanced=reform_balanced
performance=reform_performance

[battery]
# PPD = TuneD
power-saver=reform_powersave
balanced=reform_balanced
performance=reform_performance

