# imx8mq-mnt-reform2
pwm_imx27
nwl-dsi
ti-sn65dsi86
imx-dcss
panel-edp
mux-mmio
mxsfb
usbhid
imx8mq-interconnect
# meson-g12b-bananapi-cm4-mnt-reform2
meson_dw_hdmi
meson_dw_mipi_dsi
meson_canvas
meson_drm
dw_hdmi_i2s_audio
dw_mipi_dsi
meson_dw_mipi_dsi
meson_vdec
ao_cec_g12a
panfrost
snd_soc_meson_g12a_tohdmimix
dw_hdmi_i2s_audio
cec
snd_soc_hdmi_codec
snd_soc_meson_codec_glue
snd_soc_meson_axg_toddr
snd_pcm
snd
display_connector
# ls1028a
cdns_mhdp_imx
cdns_mhdp_drmcore
mali_dp
# imx8mp-mnt-reform/pocket-reform
governor_userspace
cpufreq_dt
imx_bus
