#!/bin/sh
# SPDX-License-Identifier: GPL-3.0+
# Copyright 2023-2025 Johannes Schauer Marin Rodrigues <josch@mister-muffin.de>

case $1 in prereqs) exit 0 ;; esac

# shellcheck disable=SC1091
. /scripts/functions

MACHINE=
if [ -e /etc/flash-kernel/machine ]; then
  MACHINE=$(cat /etc/flash-kernel/machine)
elif [ -e /proc/device-tree/model ]; then
  MACHINE=$(cat /proc/device-tree/model)
fi

case $MACHINE in
  "MNT Reform 2 with LS1028A Module")
    # https://source.mnt.re/reform/reform-debian-packages/-/issues/5
    dmesg -n 7 || echo "E: failed to set kernel loglevel" >&2
    ;;
esac
