# Enable hardware video decoding on MNT Reform (remove if you experience problems)
hwdec=auto

# Limit video resolution for content downloaded with youtube-dl/yt-dlp
ytdl-format=bestvideo[height<=?1080]+bestaudio/best
