SectionDevice."Headphones" {
  Comment "Headphones"

  EnableSequence [
    cset "name='Speaker Driver Playback Switch' off"
    cset "name='Speaker Switch' on"

    cset "name='HP Driver Playback Switch' on"
    cset "name='HP Left Switch' on"
    cset "name='HP Right Switch' on"

    cset "name='Output Left From Left DAC' on"
    cset "name='Output Right From Right DAC' on"
    cset "name='DAC Playback Volume' 127"
    cset "name='HP Driver Playback Volume' 0"
    cset "name='HP Analog Playback Volume' 127"
    cset "name='Speaker Analog Playback Volume' 127"
    cset "name='Speaker Driver Playback Volume' 0"
  ]

  DisableSequence [
  ]

  Value {
    PlaybackPCM "hw:${CardId}"
  }
}

SectionDevice."Speaker" {
  Comment "Speaker"

  EnableSequence [
    cset "name='HP Driver Playback Switch' off"
    cset "name='HP Left Switch' off"
    cset "name='HP Right Switch' off"

    cset "name='Speaker Driver Playback Switch' on"
    cset "name='Speaker Switch' on"

    cset "name='Output Left From Left DAC' on"
    cset "name='Output Right From Right DAC' on"
    cset "name='DAC Playback Volume' 127"
    cset "name='HP Driver Playback Volume' 0"
    cset "name='HP Analog Playback Volume' 127"
    cset "name='Speaker Analog Playback Volume' 127"
    cset "name='Speaker Driver Playback Volume' 0"
  ]

  DisableSequence [
  ]

  Value {
    PlaybackPCM "hw:${CardId}"
  }
}
