#
# tuned configuration
#
[main]
include = powersave

[cpu]
governor = powersave

[sysfs]
/sys/devices/platform/fb000000.gpu/devfreq/fb000000.gpu/governor = userspace
/sys/devices/platform/fb000000.gpu/devfreq/fb000000.gpu/min_freq = 300000000
/sys/devices/platform/fb000000.gpu/devfreq/fb000000.gpu/max_freq = 300000000

