monitor.alsa.rules = [
	{
		matches = [
			{
				node.name = "alsa_output.platform-hdmi1-sound.stereo-fallback"
			}
		]
		actions = {
			update-props = {
				priority.driver = 100
				priority.session = 100
			}
		}
	}
]
