#!/bin/sh

case "$1" in
	pre)
		echo 0003:03EB:2041.0002 >/sys/bus/hid/drivers/hid-generic/unbind
		echo 0003:03EB:2042.0001 >/sys/bus/hid/drivers/hid-generic/unbind
		;;
	post)
		echo 0003:03EB:2041.0002 >/sys/bus/hid/drivers/hid-generic/bind
		echo 0003:03EB:2042.0001 >/sys/bus/hid/drivers/hid-generic/bind
		;;
esac
