# Defaults for the MNT Reform family of computers.
# You can override these settings on your system using
# /etc/systemd/sleep.conf. See systemd-sleep.conf(5) for details.

[Sleep]
AllowHibernation=no
AllowSuspendThenHibernate=no
AllowHybridSleep=no
SuspendState=mem
