#!/bin/sh
#
# MNT Reform: Send poweroff command to the system controller via the keyboard
#

sync

if [ "$1" = "halt" ] || [ "$1" = "poweroff" ]; then
	for f in /dev/hidraw*; do
		[ -c "$f" ] || continue
		echo 'xPWR0' > "$f"
	done
fi
