Include.rxminit.File "/codecs/qcom-lpass/rx-macro/init.conf"

SectionVerb {
	Value {
		TQ "HiFi"
	}

	EnableSequence [
		cset "name='PRI_MI2S_RX Audio Mixer MultiMedia1' on"
	]

}

SectionDevice."Speaker" {
	Comment "Speaker"

	Include.rxmhpe.File "/codecs/qcom-lpass/rx-macro/HeadphoneEnableSeq.conf"
	Include.rxmhpd.File "/codecs/qcom-lpass/rx-macro/HeadphoneDisableSeq.conf"

	EnableSequence [
	]

	DisableSequence [
	]

	Value {
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels 2
	}
}

SectionDevice."Headphones" {
	Comment "Headphones"

	Include.rxmhpe2.File "/codecs/qcom-lpass/rx-macro/HeadphoneEnableSeq.conf"
	Include.rxmhpd2.File "/codecs/qcom-lpass/rx-macro/HeadphoneDisableSeq.conf"

	EnableSequence [
	]

	DisableSequence [
	]

	Value {
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels 2
	}
}

