#!/bin/bash

set -e

if [ "$EUID" -ne 0 ]
  then echo "reform-setup-encrypted-nvme has to be run as root / using sudo."
  exit
fi

command -v "cryptsetup" >/dev/null 2>&1 || { echo >&2 "Please install \"cryptsetup\" using: apt install cryptsetup"; exit 1; }
command -v "lvchange" >/dev/null 2>&1 || { echo >&2 "Please install \"lvm2\" using: apt install lvm2"; exit 1; }
command -v "mkfs.ext4" >/dev/null 2>&1 || { echo >&2 "Please install \"e2fsprogs\" using: apt install e2fsprogs"; exit 1; }

echo "This will ERASE ALL DATA from your NVMe SSD."

echo ""

read -r -p "Are you sure you want to proceed? [y/N] " response

if [[ "$response" != "y" ]]
then
        echo "Exiting."
        exit
fi

if [ -n "$(lsblk --noheadings --output=MOUNTPOINT /dev/nvme0n1)" ]; then
	echo "/dev/nvme0n1 is still in use" >&2
	exit 1
fi

cryptsetup luksFormat /dev/nvme0n1
cryptsetup luksOpen /dev/nvme0n1 reform_crypt
pvcreate /dev/mapper/reform_crypt
vgcreate reformvg /dev/mapper/reform_crypt
lvcreate --name swap --size 8G reformvg
mkswap /dev/reformvg/swap
lvcreate --name root --extents 100%FREE reformvg
mkfs.ext4 /dev/reformvg/root
SWAPUUID=$(blkid -s UUID -o value /dev/reformvg/swap)
CRYPTUUID=$(blkid -s UUID -o value /dev/nvme0n1)

echo ""
read -r -p "The encrypted NVMe is now set up. Do you want me to run reform-migrate now as well? [y/N]" response

if [[ "$response" != "y" ]]
then
	echo "If you want to migrate this system to NVMe SSD you can now run:"
	echo ""
	echo "echo RESUME=UUID=$SWAPUUID > /etc/initramfs-tools/conf.d/resume"
	echo "echo reform_crypt UUID=$CRYPTUUID none luks,discard > /etc/crypttab"
	echo "echo UUID=$SWAPUUID none swap sw 0 0 >> /etc/fstab"
	echo "cryptsetup luksOpen /dev/nvme0n1 reform_crypt"
	echo "vgchange -ay reformvg"
	echo "reform-migrate /dev/reformvg/root"
	echo "vgchange -an reformvg"
	echo "cryptsetup luksClose reform_crypt"
else
	if mountpoint --quiet /mnt; then
		echo "/mnt already has something mounted on it" >&2
		exit 1
	fi
	mount /dev/reformvg/root /mnt
	rsync -axHAWXS --numeric-ids --info=progress2 / /mnt/
	echo RESUME=UUID=$SWAPUUID > /mnt/etc/initramfs-tools/conf.d/resume
	echo reform_crypt UUID=$CRYPTUUID none luks,discard > /mnt/etc/crypttab
	echo UUID=$SWAPUUID none swap sw 0 0 >> /mnt/etc/fstab
	umount /mnt

	read -r -p "Your /boot partition will be on the SD-Card by default. Do you want it on eMMC instead? [y/N]" response
	if [[ "$response" != "y" ]]; then
		reform-boot-config /dev/reformvg/root
	else
		reform-boot-config --emmc /dev/reformvg/root
		echo "Make sure that your DIP switch has been set to OFF."
	fi
fi

vgchange -an reformvg
cryptsetup luksClose reform_crypt

echo "You can now reboot into your encrypted System."
