#!/bin/sh

set -u

init_a311d() {
    # A311D sound controls
    # without setting these, there is no UCM profile and messages like this are produced:
    # no backend DAIs enabled for fe.dai-link-0, possibly missing ALSA mixer-based routing or UCM profile
    amixer -c 0 sset 'FRDDR_A SINK 1 SEL' 'OUT 1'
    amixer -c 0 sset 'FRDDR_A SRC 1 EN' 'on'
    amixer -c 0 sset 'TDMOUT_B SRC SEL' 'IN 0'
    amixer -c 0 sset 'TDMIN_B SRC SEL' 'IN 1'
    amixer -c 0 sset 'TODDR_A SRC SEL' 'IN 1'

    # Workaround for ethernet PHY reset problem
    rmmod dwmac_meson8b dwmac_generic stmmac_platform stmmac mdio_mux_meson_g12a mdio_mux of_mdio
    sleep 0.5
    modprobe mdio_mux_meson_g12a
    modprobe dwmac_meson8b
}

init_wm8960() {
    # Fix WM8960 being too quiet
    amixer -c 0 sset Playback 255
    amixer -c 0 sset 'Left Output Mixer PCM' on
    amixer -c 0 sset 'Right Output Mixer PCM' on
    # This switch in WM8960 needs to be on for the headset mic input to work
    amixer -c 0 sset 'Left Input Mixer Boost' on
}

init_tlv320aic3100() {
    # Set up speaker on MNT Pocket Reform
    amixer -c 0 sset 'Speaker Driver' on
    amixer -c 0 sset 'Output Left From Left DAC' on
    amixer -c 0 sset 'Output Right From Right DAC' on
    amixer -c 0 sset 'Speaker Analog' 127
    amixer -c 0 sset 'DAC' 127
    amixer -c 0 sset 'HP Analog' 127
    amixer -c 0 sset 'HP Driver' on
    amixer -c 0 sset 'HP Left' on
    amixer -c 0 sset 'HP Right' on
}

init_pocket_display() {
    # Increase console font size (MNT Pocket Reform has a Hi-DPI display)
    for c in 1 2 3 4 5 6 7
        do setfont -C /dev/tty$c /usr/share/consolefonts/Uni2-TerminusBold32x16.psf.gz
    done
}

init_qca9377_wifi() {
    # load out-of-tree Wi-Fi driver
    KERNVER=$(dpkg-query --show --showformat '${Version}' "linux-image-$(uname -r)")
    modprobe cfg80211
    insmod -f "/opt/reform-qcacld2/qcacld2-${KERNVER}.ko"
}

case "$(cat /proc/device-tree/model)" in
"MNT Reform 2"|"MNT Reform 2 HDMI")
    # Workaround for WM8960 sometimes not coming out of reset
    echo 2-001a > /sys/bus/i2c/drivers/wm8960/bind

    init_wm8960

    # Enable wakeup from suspend on all UARTs (i.MX8MQ)
    # kernel 6.8 changed the /sys path for the serial lines from
    # /sys/devices/platform/soc@0/30800000.bus/308?0000.serial/tty/ttymxc?/power/wakeup
    # to
    # /sys/devices/platform/soc@0/30800000.bus/308?0000.serial/308?0000.serial:0/308?0000.serial:0.0/tty/ttymxc?/power/wakeup
    # use `find` to acquire either path
    find /sys/devices/platform/soc@0/30800000.bus/308?0000.serial/ -wholename '*/tty/ttymxc?/power/wakeup' \
	| while read -r f; do
		[ -e "$f" ] || continue
		echo enabled > "$f"
	done
    ;;
"MNT Reform 2 with BPI-CM4 Module")
    # Workaround for WM8960 sometimes not coming out of reset
    echo 1-001a > /sys/bus/i2c/drivers/wm8960/bind

    init_a311d
    init_wm8960
    ;;
"MNT Reform 2 with LS1028A Module")
    # Workaround for a DWC3 USB Controller regression

    # Assert USB hub reset
    gpioset 2 13=0
    # Reload DWC3 module
    rmmod dwc3
    modprobe dwc3
    # Deassert USB hub reset
    gpioset 2 13=1

    # Select "ondemand" CPU frequency scaling governor
    echo ondemand > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
    ;;
"MNT Pocket Reform with i.MX8MP Module")
    init_pocket_display
    init_qca9377_wifi
    init_tlv320aic3100
    ;;
"MNT Pocket Reform with BPI-CM4 Module")
    init_pocket_display
    init_a311d
    init_tlv320aic3100
    ;;
"MNT Reform 2 with i.MX8MP Module")
    init_wm8960
    init_qca9377_wifi
    ;;
"MNT Reform 2 with RCORE RK3588 Module")
    init_wm8960
    ;;
esac
