#!/bin/bash

set -e

if [ "$EUID" -ne 0 ]
  then echo "reform-display-config has to be run as root / using sudo."
  exit
fi

CHOICE="$1"
BOOTPART="mmcblk1p1"
BOOTDISK="SD card"

if [[ "--emmc" == "$1" ]]
then
    CHOICE="$2"
    BOOTPART="mmcblk0p1"
    BOOTDISK="eMMC"
fi

case "$CHOICE" in
	dual) echo "MNT Reform 2 HDMI" > /etc/flash-kernel/machine;;
	single) echo "MNT Reform 2" > /etc/flash-kernel/machine;;
	*)
		echo "Usage: "
		echo "  reform-display-config dual                Select dual-display support (internal + HDMI)."
		echo "  reform-display-config single              Select only internal display (turns off HDMI)."
		echo "  reform-display-config --emmc dual|single  Record choice on eMMC."
		exit
		;;
esac

if findmnt --noheadings --source /dev/$BOOTPART --mountpoint /boot >/dev/null
then
	update-initramfs -u
	echo "Restart MNT Reform (type: reboot) after saving your work to activate the changes."
	exit
fi

echo "Assuming boot files are on $BOOTDISK, but your system is not. Mounting /dev/$BOOTPART on /boot."

mount /dev/$BOOTPART /boot

update-initramfs -u
echo "Restart MNT Reform (type: reboot) after saving your work to activate the changes."
umount /boot
