#!/bin/bash

set -e

TARGET="$1"

echo ""
echo "This script can copy your current OS and files to a different disk, such as an SSD installed in MNT Reform."
echo ""
echo "Warning: This will overwrite files on the target partition. Make sure you know what you're doing!"
echo ""
echo "Before using this script, your target partition has to be formatted. You can use the gnome-disks program for that."
echo "gnome-disks can also help you set up an encrypted disk. You can also run the following commands for one single"
echo "partition on NVMe:"
echo ""
echo "    parted /dev/nvme0n1 \"mklabel msdos\""
echo "    parted /dev/nvme0n1 \"mkpart primary ext4 4MiB -1\""
echo "    mkfs.ext4 /dev/nvme0n1p1"
echo ""
echo "You can also setup an encrypted NVMe SSD by running reform-setup-encrypted-nvme"
echo ""

if [ -z "$TARGET" ]
then
	echo "Usage:"
	echo "  reform-migrate /dev/nvme0n1p1     Mounts the first partition of an NVMe disk and mirrors your system to it."
	echo "  reform-migrate /dev/mapper/crypt  Mounts encrypted disk 'crypt' and mirrors your system to it."
	echo "                                    The disk has to be unlocked first with:"
	echo "                                      cryptsetup luksOpen /dev/nvme0n1p1 crypt"
	echo ""
	exit
fi

if [ ! -e "$TARGET" ]
then
	echo "Error: The partition $TARGET does not exist."
	exit
fi

if [ "$EUID" -ne 0 ]
  then echo "reform-migrate has to be run as root / using sudo."
  exit
fi

if mountpoint --quiet /mnt; then
	echo "/mnt already has something mounted on it" >&2
	exit 1
fi

command -v "rsync" >/dev/null 2>&1 || { echo >&2 "Please install \"rsync\" using: apt install rsync"; exit 1; }

SWAP=
if findmnt --fstab --types swap >/dev/null; then
	SWAP="$(findmnt --noheadings --fstab --types swap --output SOURCE,TARGET,FSTYPE,OPTIONS,FREQ,PASSNO)"
fi

sed -i -e 's/^/#/' /etc/fstab
cat << END >> /etc/fstab
$TARGET / auto errors=remount-ro 0 1
/dev/mmcblk1p1 /boot auto errors=remount-ro 0 1
END

if [ -n "$SWAP" ]; then
	echo "$SWAP" >> /etc/fstab
fi

update-initramfs -u

echo "Trying to mount $TARGET... (if this fails, format the disk/partition as explained above)"

mount "$TARGET" /mnt

echo "Target partition successfully mounted. The next step will copy all your files over to the target, overwriting existing files in the process."
echo ""

read -r -p "Are you sure you want to proceed? [y/N] " response

if [[ "$response" != "y" ]]
then
	echo "Exiting."
	umount /mnt
	exit
fi

echo "Starting the copy. This can take a while."

rsync -axHAWXS --numeric-ids --info=progress2 / /mnt/

echo "Files copied."

umount /mnt

echo "$TARGET unmounted."
