#!/bin/bash

set -e

if [ "$EUID" -ne 0 ]
  then echo "reform-display-config has to be run as root / using sudo."
  exit
fi

CHOICE="$1"
BOOTPART="mmcblk1p1"
BOOTDISK="SD card"

if [[ "--emmc" == "$1" ]]; then
	CHOICE="$2"
	BOOTPART="mmcblk0p1"
	BOOTDISK="eMMC"

	if [ ! -b "/dev/mmcblk0p1" ]; then
		echo "/dev/mmcblk0p1 doesn't exist -- run reform-flash-rescue" >&2
		exit 1
	fi
fi

case "$CHOICE" in
	dual) echo "MNT Reform 2 HDMI" > /etc/flash-kernel/machine;;
	single) echo "MNT Reform 2" > /etc/flash-kernel/machine;;
	*)
		echo "Usage: "
		echo "  reform-display-config dual                Select dual-display support (internal + HDMI)."
		echo "  reform-display-config single              Select only internal display (turns off HDMI)."
		echo "  reform-display-config --emmc dual|single  Record choice on eMMC."
		exit
		;;
esac

if findmnt --noheadings --source /dev/$BOOTPART --mountpoint /boot >/dev/null
then
	update-initramfs -u
else
	echo "Assuming boot files are on $BOOTDISK, but your system doesn't have it mounted." >&2
	echo "Mounting /dev/$BOOTPART on /boot." >&2

	if mountpoint --quiet /boot; then
		echo "/boot already has something mounted on it" >&2
		exit 1
	fi

	if [ -n "$(lsblk --noheadings --output=MOUNTPOINT /dev/$BOOTPART)" ]; then
		echo "/dev/$BOOTPART is still in use" >&2
		exit 1
	fi

	trap "umount /boot" EXIT INT TERM
	mount /dev/$BOOTPART /boot
	update-initramfs -u
	trap - EXIT INT TERM
	umount /boot
fi

if [ "--emmc" = "$1" ]; then
	echo "Your /boot partition is on emmc (/dev/$BOOTPART)." >&2
	echo "Make sure that your DIP switch has been set to OFF." >&2
else
	echo "Your /boot partition is on your SD-Card (/dev/$BOOTPART)." >&2
	echo "Make sure that your DIP switch has been set to ON." >&2
fi

echo "Restart MNT Reform (type: reboot) after saving your work to activate the changes."
