#!/bin/sh

set -eu

if [ "$(id -u)" -ne 0 ]
  then echo "reform-boot-config has to be run as root / using sudo."
  exit
fi

echo "This script selects your preferred boot medium. It writes your choice to the file /etc/fstab"
echo

usage() {
	echo "Usage: " >&2
	echo "  reform-boot-config [--emmc] sd   Boot from SD card (default)." >&2
	echo "  reform-boot-config [--emmc] nvme Boot from NVMe SSD." >&2
	echo "  reform-boot-config [--emmc] usb  Boot from USB storage device." >&2
	echo "  reform-boot-config [--emmc] emmc Boot from eMMC." >&2
	echo "" >&2
	echo "      --emmc Record boot preference on eMMC instead of SD card." >&2
	echo "             This is only useful with SoM dip switch turned off." >&2
	echo "" >&2
	echo "Choosing sd, nvme, usb or emmc will set the root partition to" >&2
	echo "/dev/mmcblk1p2, /dev/nvme0n1p1, /dev/sda1 or /dev/mmcblk0p2," >&2
	echo "respectively.i You can choose another root partition by passing" >&2
	echo "the absolute device path starting with /dev/ explicitly." >&2
	echo "For example, to boot from an LVM volume, run:" >&2
	echo "" >&2
	echo "    reform-boot-config /dev/reformvg/root" >&2
}

if [ $# -ne 1 ] && [ $# -ne 2 ]; then
	usage
	exit 1
fi

BOOTPREF="$1"
BOOTPART="mmcblk1p1"

if [ "--emmc" = "$1" ]
then
	BOOTPREF="$2"
	BOOTPART="mmcblk0p1"

	if [ ! -b "/dev/mmcblk0p1" ]; then
		echo "/dev/mmcblk0p1 doesn't exist -- run reform-flash-rescue" >&2
		exit 1
	fi
fi

if mountpoint --quiet /mnt; then
	echo "/mnt already has something mounted on it" >&2
	exit 1
fi

case $BOOTPREF in
	sd)   : "${ROOTPART:=mmcblk1p2}";;
	nvme) : "${ROOTPART:=nvme0n1p1}";;
	usb)  : "${ROOTPART:=sda1}";;
	emmc) : "${ROOTPART:=mmcblk0p2}";;
	/dev/*)
		if [ ! -b "$BOOTPREF" ]; then
			echo "there is no block device called $BOOTPREF" >&2
			exit 1
		fi
		: "${ROOTPART:=$BOOTPREF}"
		;;
	*) usage; exit 1;;
esac

ROOTPART="${ROOTPART#/dev/}"

if [ -n "$(lsblk --noheadings --output=MOUNTPOINT /dev/$ROOTPART)" ]; then
	echo "/dev/$ROOTPART is still in use" >&2
	exit 1
fi

if [ -n "$(lsblk --noheadings --output=MOUNTPOINT /dev/$BOOTPART)" ]; then
	echo "/dev/$BOOTPART is still in use" >&2
	echo "Proceeding will unmount /dev/$BOOTPART so that it can be used as your new /boot." >&2
	echo "Since your current system is using it, this system might become unusable." >&2
	echo "You might not want to proceed if you care about your currently running system." >&2
	printf "Do you really want to continue? [y/N] " >&2
	read answer
	if [ "$answer" != "${answer#[Yy]}" ]; then
		umount /dev/$BOOTPART
	else
		exit 1
	fi
fi

# make sure it's unused now after unmounting
if [ -n "$(lsblk --noheadings --output=MOUNTPOINT /dev/$BOOTPART)" ]; then
	echo "/dev/$BOOTPART is still in use" >&2
	exit 1
fi

cleanup() {
	umount /mnt/boot || :
	umount /mnt/dev || :
	umount /mnt/sys || :
	umount /mnt/proc || :
	umount /mnt || :
}

trap cleanup EXIT INT TERM

mount /dev/$ROOTPART /mnt
mount /dev/$BOOTPART /mnt/boot
mount -o bind /dev /mnt/dev
mount -t sysfs sys /mnt/sys
mount -t proc proc /mnt/proc


if LIBMOUNT_FSTAB=/mnt/etc/fstab findmnt --fstab --noheadings --source "/dev/$ROOTPART" --mountpoint / >/dev/null && \
	LIBMOUNT_FSTAB=/mnt/etc/fstab findmnt --fstab --noheadings --source "/dev/$BOOTPART" --mountpoint /boot >/dev/null; then
	echo "/etc/fstab already contains the correct entries" >&2
else
	echo "commenting original /etc/fstab contents" >&2

	SWAP=
	if LIBMOUNT_FSTAB=/mnt/etc/fstab findmnt --fstab --types swap >/dev/null; then
		SWAP="$(LIBMOUNT_FSTAB=/mnt/etc/fstab findmnt --noheadings --fstab --types swap --output SOURCE,TARGET,FSTYPE,OPTIONS,FREQ,PASSNO)"
	fi

	sed -i -e 's/^/#/' /mnt/etc/fstab
	cat << END >> /mnt/etc/fstab
/dev/$ROOTPART / auto errors=remount-ro 0 1
/dev/$BOOTPART /boot auto errors=remount-ro 0 1
END

	if [ -n "$SWAP" ]; then
		echo "$SWAP" >> /mnt/etc/fstab
	fi
fi

chroot /mnt update-initramfs -u

if [ "--emmc" = "$1" ]; then
	echo "Your /boot partition is on emmc (/dev/$BOOTPART)." >&2
	echo "Make sure that your DIP switch has been set to OFF." >&2
else
	echo "Your /boot partition is on your SD-Card (/dev/$BOOTPART)." >&2
	echo "Make sure that your DIP switch has been set to ON." >&2
fi

echo "Restart MNT Reform (type: reboot) after saving your work to activate the changes."
