#!/bin/bash

set -e

MACHINE=$(tr -d '\0' < /proc/device-tree/model)
if [ "MNT Reform 2" != "$MACHINE" ] && [ "MNT Reform 2 HDMI" != "$MACHINE" ]
  then echo "Sorry, reform-flash-rescue is only supported on MNT Reform 2 with i.MX8MQ processor module."
  exit
fi

if [ ! -e /sys/class/block/mmcblk0boot0/force_ro ]; then
	echo "/sys/class/block/mmcblk0boot0/force_ro doesn't exist" >&2
	exit 1
fi

if [ ! -w /sys/class/block/mmcblk0boot0/force_ro ]; then
	echo "/sys/class/block/mmcblk0boot0/force_ro is not writable" >&2
	exit 1
fi

if [ ! -e /boot/flash.bin ]; then
	echo "/boot/flash.bin doesn't exist" >&2
	exit 1
fi

for p in mmcblk0 mmcblk0p1 mmcblk0p2 mmcblk0boot0 mmcblk0boot1; do
	if [ -n "$(lsblk --noheadings --output=MOUNTPOINT "/dev/$p")" ]; then
		echo "/dev/$p is still in use" >&2
		exit 1
	fi
done

echo "WARNING: This overwrites the bootloader on the eMMC rescue disk with the" >&2
echo "backup stored as /boot/flash.bin!" >&2

read -r -p "Are you sure you want to proceed? [y/N] " response

if [[ "$response" != "y" ]]
then
        echo "Exiting."
        exit
fi

reform-flash-uboot --offline emmc

echo "Bootloader was successfully written to /dev/mmcblk0boot0." >&2
echo "" >&2

echo "Do you want to download and install the latest sysimage-v3 to eMMC as well?" >&2
echo "This step needs a working internet connection and either wget or curl installed." >&2
echo "" >&2
echo "WARNING: This overwrites partitions on eMMC, deleting all data." >&2
read -r -p "Are you sure you want to proceed? [y/N] " response

if [[ "$response" != "y" ]]
then
        echo "Exiting."
        exit
fi

URL="https://source.mnt.re/reform/reform-system-image/-/jobs/artifacts/main/raw/reform2-imx8mq/reform-rescue-system.img.gz?job=build"

{
if curl --version >/dev/null; then
	curl --silent --location "$URL"
elif wget --version >/dev/null; then
	wget --quiet --output-document=- "$URL"
else
	echo "need curl or wget" >&2
	exit 1
fi; } | gzip --decompress --to-stdout | dd of=/dev/mmcblk0 status=progress
partprobe /dev/mmcblk0

# The rescue system image that we downloaded and wrote to the eMMC above is
# configured to use the rootfs on the SD-Card but we want the initramfs on eMMC
# to boot the rootfs on eMMC and not the rootfs from SD-Card.  Use
# reform-boot-config to update the /etc/fstab and initramfs to use the eMMC
reform-boot-config --emmc emmc

echo "If the SoM dip switch is turned off and no SD-Card is present, your" >&2
echo "system will now boot from eMMC and load the rootfs from there as well." >&2
echo "If you want to boot from eMMC but load the rootfs from elsewhere, run" >&2
echo "reform-boot-config with the --emmc switch." >&2
