#!/bin/bash
#
# MNT Reform Power Daemon
#
# A prototype daemon for managing power consumption on MNT Pocket Reform, with the goals of:
#
# - avoiding SoC resets due to current spikes causing voltage dips on 5V rail, on low battery voltage
# - prolonging runtime on battery
#

trap exit SIGINT SIGTERM

if ! grep "MNT Pocket Reform with RCORE RK3588 Module" /proc/device-tree/model; then
		echo "Fatal: reform-power-daemon currently supports only MNT Pocket Reform with RCORE RK3588 Module."
		exit 1
fi

if ! lsmod | grep reform2_lpc; then
		echo "Fatal: reform2_lpc module not loaded. Please reinstall reform2-lpc-dkms and reboot." >&2
		exit 1
fi

# TODO: check sysctl and keyboard firmware versions
# and complain if they're not recent enough

bat_path="/sys/class/power_supply/BAT0"
gpu_path="/sys/devices/platform/fb000000.gpu/devfreq/fb000000.gpu"
cpu_path="/sys/devices/system/cpu/cpufreq"
prev_status=""

bat_max_gpu_freq="300000000"
bat_display_backlight_level="40%"
bat_keyboard_backlight='xLRGB\x05\x00\x05'
ac_display_backlight_level="70%"
ac_max_gpu_freq="1000000000"
ac_cpu_governor="schedutil" # could also be: "performance"
ac_keyboard_backlight='xLRGB\x20\x00\x20'

while true; do
		bat_status=$(cat $bat_path/status)

		if [ "$bat_status" != "$prev_status" ]; then
				echo "Battery status changed to $bat_status."

				# on AC power?
				#
				# - set GPU governor to userspace
				#		- set GPU max freq to 1000 MHz
				# - set CPU governor to powersave
				
				if [ "$bat_status" == "Charging" ]; then
						echo "simple_ondemand" > "$gpu_path/governor"
						echo "300000000" > "$gpu_path/min_freq"
						echo "$ac_max_gpu_freq" > "$gpu_path/max_freq"
						brightnessctl set "$ac_display_backlight_level"
						printf "$ac_keyboard_backlight" > /dev/hidraw0
						
						for i in 0 4 6; do
								echo "$ac_cpu_governor" > "$cpu_path/policy$i/scaling_governor"
						done
				fi

				# on battery power?
				#
				# - set GPU governor to userspace
				#		- set GPU max freq to 300 MHz
				# - set CPU governor to powersave

				if [ "$bat_status" == "Discharging" ]; then
						echo "userspace" > "$gpu_path/governor"
						echo "300000000" > "$gpu_path/min_freq"
						echo "$bat_max_gpu_freq" > "$gpu_path/max_freq"
						brightnessctl set "$bat_display_backlight_level"
						printf "$bat_keyboard_backlight" > /dev/hidraw0

						for i in 0 4 6; do
								echo "powersave" > "$cpu_path/policy$i/scaling_governor"
						done
				fi
		fi

		prev_status="$bat_status"
		sleep 1
done
