# empty SYSIMAGE variable because no system image is produced for
# this machine
SYSIMAGE=""
DTBPATH="freescale/imx8mq-mnt-reform2-hdmi.dtb"
EMMC_USE=true
EMMC_BOOT=true
SD_BOOT=true
# name of devices in /dev
DEV_MMC="mmcblk0"
DEV_MMC_BOOT0=true
DEV_SD="mmcblk1"
DEV_SSD="nvme0n1"
DEV_USB="sda"
# the current u-boot hashes from source.mnt.re
BOOTLOADER_SHA1="757f73b71c1009a1baa0d90a8f0bcb494e4b1936"
BOOTLOADER_PROJECT="reform-boundary-uboot"
BOOTLOADER_TAG="2026-01-11"
BOOTLOADER_OFFSET=33792
FLASHBIN_OFFSET=0
NEED_NONFREE=false
BOOTARGS="ro no_console_suspend cryptomgr.notests console=ttymxc0,115200 cma=512M pci=nomsi plymouth.ignore-serial-consoles pcie_aspm=off console=tty1"
