# name of the system image file produced by reform-system-image
SYSIMAGE="reform-system-imx8mp"
DTBPATH="freescale/imx8mp-mnt-reform2.dtb"
EMMC_USE=true
EMMC_BOOT=false
SD_BOOT=false
# name of devices in /dev
DEV_MMC="mmcblk2"
DEV_SD="mmcblk0"
DEV_SSD="nvme0n1"
DEV_USB="sda"
# the current u-boot hashes from source.mnt.re
UBOOT_SHA1="5c5bbf5214c79535a274dfbcfd748b927e7c919a"
UBOOT_PROJECT="reform-imx8mp-uboot"
UBOOT_TAG="2024-05-06"
UBOOT_OFFSET=0
FLASHBIN_OFFSET=0
NEED_NONFREE=false
BOOTARGS="ro no_console_suspend cryptomgr.notests loglevel=3 pci=pcie_bus_perf nvme_core.default_ps_max_latency_us=0 console=tty1 cma=256MB"
