# name of the system image file produced by reform-system-image
SYSIMAGE="reform-system-a311d"
DTBPATH="amlogic/meson-g12b-bananapi-cm4-mnt-reform2.dtb"
# flashing the reform-system-image to emmc also flashes u-boot which might
# soft-brick the module if something goes wrong
EMMC_USE=false
EMMC_BOOT=false
SD_BOOT=true
# name of devices in /dev
DEV_MMC="mmcblk1"
DEV_SD="mmcblk0"
DEV_SSD="nvme0n1"
DEV_USB="sda"
# the current u-boot hashes from source.mnt.re
UBOOT_SHA1="ce6a1d18fdc3a89ed916613201bfc35d288bd99d"
UBOOT_PROJECT="reform-a311d-uboot"
UBOOT_TAG="2024-06-30"
UBOOT_OFFSET=512
FLASHBIN_OFFSET=512
# non-free-firmware is required for firmware-realtek
NEED_NONFREE=true
BOOTARGS="ro no_console_suspend cryptomgr.notests loglevel=3 console=ttyAML0,115200 pci=pcie_bus_perf libata.force=noncq nvme_core.default_ps_max_latency_us=0 console=tty1"
