# name of the system image file produced by reform-system-image
SYSIMAGE="reform-system-imx8mp"
DTBPATH="freescale/imx8mp-mnt-reform2.dtb"
EMMC_USE=true
EMMC_BOOT=true
SD_BOOT=false
# name of devices in /dev
DEV_MMC="mmcblk0"
DEV_SD="mmcblk1"
DEV_SSD="nvme0n1"
DEV_USB="sda"
# the current u-boot hashes from source.mnt.re
UBOOT_SHA1= # FIXME
UBOOT_PROJECT= # FIXME
UBOOT_TAG= # FIXME
UBOOT_OFFSET=33792
FLASHBIN_OFFSET=0
NEED_NONFREE=false
