# name of the system image file produced by reform-system-image
SYSIMAGE="reform-system-imx8mq"
DTBPATH="freescale/imx8mq-mnt-reform2.dtb"
EMMC_USE=true
EMMC_BOOT=true
# name of devices in /dev
DEV_MMC="mmcblk0"
DEV_SD="mmcblk1"
DEV_SSD="nvme0n1"
DEV_USB="sda"
# the current u-boot hashes from source.mnt.re
UBOOT_SHA1="3de987054676b65b80ecb65455465326c9539928"
UBOOT_PROJECT="reform-boundary-uboot"
UBOOT_TAG="2023-10-18"
UBOOT_OFFSET=33792
FLASHBIN_OFFSET=0
NEED_NONFREE=false
