# name of the system image file produced by reform-system-image
SYSIMAGE="reform-system-imx8mq"
DTBPATH="freescale/imx8mq-mnt-reform2.dtb"
EMMC_USE=true
EMMC_BOOT=true
SD_BOOT=true
# name of devices in /dev
DEV_MMC="mmcblk0"
DEV_SD="mmcblk1"
DEV_SSD="nvme0n1"
DEV_USB="sda"
# the current u-boot hashes from source.mnt.re
UBOOT_SHA1="6ce0074ac807c295f92122a5a77ce0459729deb7"
UBOOT_PROJECT="reform-boundary-uboot"
UBOOT_TAG="2024-06-30"
UBOOT_OFFSET=33792
FLASHBIN_OFFSET=0
NEED_NONFREE=false
BOOTARGS="ro no_console_suspend console=ttymxc0,115200 cma=512M pci=nomsi console=tty1"
