# name of the system image file produced by reform-system-image
SYSIMAGE="reform-system-imx8mq"
DTBPATH="freescale/imx8mq-mnt-reform2.dtb"
EMMC_USE=true
EMMC_BOOT=true
SD_BOOT=true
# name of devices in /dev
DEV_MMC="mmcblk0"
DEV_MMC_BOOT0=true
DEV_SD="mmcblk1"
DEV_SSD="nvme0n1"
DEV_USB="sda"
# the current u-boot hashes from source.mnt.re
UBOOT_SHA1="60ecf649038ebd92bfb6676bdf746daa30825dbf"
UBOOT_PROJECT="reform-boundary-uboot"
UBOOT_TAG="2024-07-19"
UBOOT_OFFSET=33792
FLASHBIN_OFFSET=0
NEED_NONFREE=false
BOOTARGS="ro no_console_suspend cryptomgr.notests console=ttymxc0,115200 cma=512M pci=nomsi console=tty1"
