# name of the system image file produced by reform-system-image
SYSIMAGE="reform-system-imx8mp"
DTBPATH="freescale/imx8mp-mnt-reform2.dtb"
EMMC_USE=true
EMMC_BOOT=warn
# prevent writing u-boot to sd-card because a) the imx8mplus will only read it
# from emmc anyways and b) because UBOOT_OFFSET=0 would overwrite the MBR on it
SD_BOOT=false
# name of devices in /dev
DEV_MMC="mmcblk2"
DEV_MMC_BOOT0=true
DEV_SD="mmcblk0"
DEV_SSD="nvme0n1"
DEV_USB="sda"
# the current u-boot hashes from source.mnt.re
UBOOT_SHA1="50f918c3a921b37f89a535a7707f3478b7d4d4b6"
UBOOT_PROJECT="reform-imx8mp-uboot"
UBOOT_TAG="2026-01-28"
# when flashing to SD-card, the correct offset is 33792
# an offset of zero would overwrite the MBR
UBOOT_OFFSET=0
FLASHBIN_OFFSET=0
NEED_NONFREE=false
BOOTARGS="ro no_console_suspend cryptomgr.notests pci=pcie_bus_perf nvme_core.default_ps_max_latency_us=0 plymouth.ignore-serial-consoles console=tty1 cma=256MB"
