# name of the system image file produced by reform-system-image
SYSIMAGE="pocket-reform-system-a311d"
DTBPATH="amlogic/meson-g12b-bananapi-cm4-mnt-pocket-reform.dtb"
# flashing the reform-system-image to emmc also flashes u-boot which might
# soft-brick the module if something goes wrong
EMMC_USE=false
EMMC_BOOT=warn
SD_BOOT=true
# name of devices in /dev
DEV_MMC="mmcblk1"
DEV_SD="mmcblk0"
DEV_SSD="nvme0n1"
DEV_USB="sda"
# the current u-boot hashes from source.mnt.re
UBOOT_SHA1="c85f532eb0559b5fc3db20271027239531c77698"
UBOOT_PROJECT="reform-a311d-uboot"
UBOOT_TAG="2024-08-01"
UBOOT_OFFSET=512
FLASHBIN_OFFSET=512
# non-free-firmware is required for firmware-realtek
NEED_NONFREE=true
BOOTARGS="ro no_console_suspend cryptomgr.notests loglevel=3 console=ttyAML0,115200 pci=pcie_bus_perf libata.force=noncq nvme_core.default_ps_max_latency_us=0 console=tty1 fbcon=rotate:3"
