#
# tuned configuration
#
[main]
include = throughput-performance

[sysfs]
/sys/devices/platform/fb000000.gpu/devfreq/fb000000.gpu/governor = userspace
/sys/devices/platform/fb000000.gpu/devfreq/fb000000.gpu/max_freq = 1000000000
/sys/devices/platform/fb000000.gpu/devfreq/fb000000.gpu/min_freq = 1000000000

