# -*- conf -*-

[main]
font=Iosevka Term:size=15
term=xterm
dpi-aware=no

# adapted from https://github.com/imcarvalho/neonpurple
# but tweaked background and regular0

[colors]
background=10022e
foreground=e5e5e6
regular0=392B57
regular1=cd0d76
regular2=09EAA5
regular3=FFFA69
regular4=05BEFF
regular5=FF00E0
regular6=9AA5ED
regular7=FFFFFF
bright0=A8FCFF
bright1=FF0EA5
bright2=00FFB7
bright3=FEF787
bright4=18CCFC
bright5=FF00F8
bright6=A6B5FF
bright7=FFFFFF
