# otherwise kernels built with CONFIG_ARM_IMX8M_DDRC_DEVFREQ=m will result in
# a system that locks up early during boot
blacklist imx8m-ddrc

# Installing the mdadm package disables the wm8960audio sound card with these
# errors on dmesg:
#   fsl-sai 308b0000.sai: Missing dma channel for stream: 0
#   fsl-sai 308b0000.sai: ASoC: error at snd_soc_pcm_component_new on 308b0000.sai: -22
#   fsl-asoc-card sound: ASoC: can't create pcm HiFi :-22
#   fsl-asoc-card sound: error -EINVAL: snd_soc_register_card failed
#   fsl-asoc-card: probe of sound failed with error -22
# It is not clear why this happens and the proper solution needs more
# investigation. Until then, disabling the raid456 module will restore audio
# at the cost of disabling raid.
blacklist raid456
